site_name: "Documentación - Cuadratura Gaussiana"

nav:
  - Introducción: index.md
  - Método Numérico: explicacion.md
  - Código: codigo.md
theme:
  name: material

markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.arithmatex
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
